FROM node:lts-alpine3.13

MAINTAINER LOC NGO <xuanloc0511@gmail.com>

RUN mkdir -p /scripts
ADD buildscript.sh /scripts/buildscript.sh
ADD packscript.sh /scripts/packscript.sh
RUN chmod 777 /scripts/buildscript.sh \
	&& chmod 777 /scripts/packscript.sh
CMD ["/bin/sh"]